#!/usr/bin/env python

__author__ = "Felix Simkovic"
__date__ = "16 Apr 2018"
__version__ = "0.1"

import logging
import sys

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger()

from src.video import VideoInSk, VideoOutSk
from src.misc import determine_droplet_sizes_in_frame, hist


if __name__ == "__main__":
    import argparse

    p = argparse.ArgumentParser()
    p.add_argument("--debug", default=False, action="store_true")
    p.add_argument("-o", "--output", help="Path for the output video file")
    p.add_argument("videos", nargs="+", help="Path to a video file")
    args = p.parse_args()
    
    radii_per_video_per_frame = []
    for vindex, video in enumerate(args.videos):
        logger.info("Working on video %d", vindex)
        #  vidout = VideoOutSk(video + "out.mp4")
        radii_per_video_per_frame.append([])
        for findex, frame in enumerate(VideoInSk(video).frames):
            if findex % 2 > 0:
                continue
            logger.debug("Processing video frame %d", findex)
            radii, frame_ = determine_droplet_sizes_in_frame(frame, debug=args.debug)
            radii_per_video_per_frame[-1].extend(radii)
            #  vidout.add(frame_)
        #  vidout.save()
        logger.info("Droplets counted in last frame: %d", len(radii_per_video_per_frame[-1]))
    
    hist(radii_per_video_per_frame)

